version: '3'
services:
    web:
        container_name: "${CONTAINER_NAME_PREFIX}-web"
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/src
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        links:
            - php
    php:
        user: "${PHP_UID}:${PHP_GID}"
        container_name: "${CONTAINER_NAME_PREFIX}-app"
        build: ./docker/php
        working_dir: /src
        volumes:
            - .:/src
    mysql:
        container_name: "${CONTAINER_NAME_PREFIX}-db"
        image: mariadb
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=root
        volumes:
            - ./docker/mysql:/var/lib/mysql
    phpmyadmin:
        container_name: "${CONTAINER_NAME_PREFIX}-phpmyadmin"
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
